# Generated by Django 2.2.3 on 2020-08-26 17:32

import cloudinary.models
import deshonnati_app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('cityid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='DailySpecialFeed',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('specialpage1', models.FileField(upload_to=deshonnati_app.models.special_directory_path)),
                ('specialpage2', models.FileField(upload_to=deshonnati_app.models.special_directory_path)),
                ('specialpage3', models.FileField(upload_to=deshonnati_app.models.special_directory_path)),
                ('specialpage4', models.FileField(upload_to=deshonnati_app.models.special_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('page1', cloudinary.models.CloudinaryField(max_length=255, verbose_name='page1')),
                ('page2', cloudinary.models.CloudinaryField(max_length=255, verbose_name='page2')),
                ('page3', cloudinary.models.CloudinaryField(max_length=255, verbose_name='page3')),
                ('page4', cloudinary.models.CloudinaryField(max_length=255, verbose_name='page4')),
                ('page5', cloudinary.models.CloudinaryField(max_length=255, verbose_name='page5')),
                ('page6', cloudinary.models.CloudinaryField(max_length=255, verbose_name='page6')),
                ('page7', cloudinary.models.CloudinaryField(max_length=255, verbose_name='page7')),
                ('page8', cloudinary.models.CloudinaryField(max_length=255, verbose_name='page8')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deshonnati_app.City')),
            ],
        ),
    ]