# Generated by Django 2.2.3 on 2020-08-29 17:17

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deshonnati_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clipimage', cloudinary.models.CloudinaryField(max_length=255, verbose_name='clipimage')),
            ],
        ),
    ]
