# Generated by Django 2.2.3 on 2020-08-30 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deshonnati_app', '0002_clipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clipping',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
