# Generated by Django 2.2.3 on 2020-09-01 04:31

import cloudinary.models
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('deshonnati_app', '0003_auto_20200830_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyspecialfeed',
            name='specialpage5',
            field=cloudinary.models.CloudinaryField(default='abc.pdf', max_length=255, verbose_name='specialpage5'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyspecialfeed',
            name='specialpage6',
            field=cloudinary.models.CloudinaryField(default=django.utils.timezone.now, max_length=255, verbose_name='specialpage6'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyspecialfeed',
            name='specialpage7',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='specialpage7'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyspecialfeed',
            name='specialpage8',
            field=cloudinary.models.CloudinaryField(default='a', max_length=255, verbose_name='specialpage8'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailyspecialfeed',
            name='specialpage1',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='specialpage1'),
        ),
        migrations.AlterField(
            model_name='dailyspecialfeed',
            name='specialpage2',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='specialpage2'),
        ),
        migrations.AlterField(
            model_name='dailyspecialfeed',
            name='specialpage3',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='specialpage3'),
        ),
        migrations.AlterField(
            model_name='dailyspecialfeed',
            name='specialpage4',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='specialpage4'),
        ),
    ]
