# Generated by Django 2.2.3 on 2020-09-01 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deshonnati_app', '0004_auto_20200901_0431'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailySpecialFeed',
        ),
    ]
