# Generated by Django 2.2.3 on 2020-09-05 18:02

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deshonnati_app', '0006_dailyspecialakola'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySpecialBuldhana',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('specialakola1', cloudinary.models.CloudinaryField(max_length=255, verbose_name='specialakola1')),
                ('specialakola2', cloudinary.models.CloudinaryField(max_length=255, verbose_name='specialakola2')),
                ('specialakola3', cloudinary.models.CloudinaryField(max_length=255, verbose_name='specialakola3')),
                ('specialakola4', cloudinary.models.CloudinaryField(max_length=255, verbose_name='specialakola4')),
                ('specialakola5', cloudinary.models.CloudinaryField(max_length=255, verbose_name='specialakola5')),
                ('specialakola6', cloudinary.models.CloudinaryField(max_length=255, verbose_name='specialakola6')),
                ('specialakola7', cloudinary.models.CloudinaryField(max_length=255, verbose_name='specialakola7')),
                ('specialakola8', cloudinary.models.CloudinaryField(max_length=255, verbose_name='specialakola8')),
            ],
        ),
    ]
