# Generated by Django 2.2.3 on 2020-09-05 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deshonnati_app', '0007_dailyspecialbuldhana'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyspecialbuldhana',
            old_name='id',
            new_name='buldhanaid',
        ),
        migrations.RenameField(
            model_name='dailyspecialbuldhana',
            old_name='specialakola1',
            new_name='specialbuldhana1',
        ),
        migrations.RenameField(
            model_name='dailyspecialbuldhana',
            old_name='specialakola2',
            new_name='specialbuldhana2',
        ),
        migrations.RenameField(
            model_name='dailyspecialbuldhana',
            old_name='specialakola3',
            new_name='specialbuldhana3',
        ),
        migrations.RenameField(
            model_name='dailyspecialbuldhana',
            old_name='specialakola4',
            new_name='specialbuldhana4',
        ),
        migrations.RenameField(
            model_name='dailyspecialbuldhana',
            old_name='specialakola5',
            new_name='specialbuldhana5',
        ),
        migrations.RenameField(
            model_name='dailyspecialbuldhana',
            old_name='specialakola6',
            new_name='specialbuldhana6',
        ),
        migrations.RenameField(
            model_name='dailyspecialbuldhana',
            old_name='specialakola7',
            new_name='specialbuldhana7',
        ),
        migrations.RenameField(
            model_name='dailyspecialbuldhana',
            old_name='specialakola8',
            new_name='specialbuldhana8',
        ),
    ]
