# Generated by Django 2.2.3 on 2020-09-27 14:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('deshonnati_app', '0008_auto_20200905_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='clipping',
            name='clipdate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
