# Generated by Django 2.2.3 on 2020-10-12 11:32

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deshonnati_app', '0009_clipping_clipdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageOneClip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_date', models.DateField()),
                ('clip_one', cloudinary.models.CloudinaryField(max_length=255, verbose_name='clip_one')),
                ('clip_two', cloudinary.models.CloudinaryField(max_length=255, verbose_name='clip_two')),
                ('clip_three', cloudinary.models.CloudinaryField(max_length=255, verbose_name='clip_three')),
                ('clip_four', cloudinary.models.CloudinaryField(max_length=255, verbose_name='clip_four')),
                ('clip_five', cloudinary.models.CloudinaryField(max_length=255, verbose_name='clip_five')),
                ('clip_six', cloudinary.models.CloudinaryField(max_length=255, verbose_name='clip_six')),
                ('clip_seven', cloudinary.models.CloudinaryField(max_length=255, verbose_name='clip_seven')),
                ('clip_eight', cloudinary.models.CloudinaryField(max_length=255, verbose_name='clip_eight')),
                ('clip_nine', cloudinary.models.CloudinaryField(max_length=255, verbose_name='clip_nine')),
            ],
        ),
        migrations.CreateModel(
            name='PageTwoClip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_two_date', models.DateField()),
                ('two_clip_one', cloudinary.models.CloudinaryField(max_length=255, verbose_name='two_clip_one')),
                ('two_clip_two', cloudinary.models.CloudinaryField(max_length=255, verbose_name='two_clip_two')),
                ('two_clip_three', cloudinary.models.CloudinaryField(max_length=255, verbose_name='two_clip_three')),
                ('two_clip_four', cloudinary.models.CloudinaryField(max_length=255, verbose_name='two_clip_four')),
                ('two_clip_five', cloudinary.models.CloudinaryField(max_length=255, verbose_name='two_clip_five')),
                ('two_clip_six', cloudinary.models.CloudinaryField(max_length=255, verbose_name='two_clip_six')),
                ('two_clip_eight', cloudinary.models.CloudinaryField(max_length=255, verbose_name='two_clip_eight')),
                ('two_clip_nine', cloudinary.models.CloudinaryField(max_length=255, verbose_name='two_clip_nine')),
                ('two_clip_ten', cloudinary.models.CloudinaryField(max_length=255, verbose_name='two_clip_ten')),
            ],
        ),
    ]
