# Generated by Django 2.2.3 on 2020-10-12 13:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deshonnati_app', '0010_pageoneclip_pagetwoclip'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagetwoclip',
            name='two_clip_seven',
            field=cloudinary.models.CloudinaryField(default='https://www.ajinkyabharat.in/static/images/MATLOGO.jpeg', max_length=255, verbose_name='two_clip_six'),
            preserve_default=False,
        ),
    ]
