# Generated by Django 2.2.3 on 2022-06-01 09:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deshonnati_app', '0013_advertisementform'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyfeed',
            name='page10',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='page10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyfeed',
            name='page11',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='page11'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyfeed',
            name='page12',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='page12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyfeed',
            name='page9',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='page9'),
            preserve_default=False,
        ),
    ]
