# Generated by Django 2.2.3 on 2022-06-18 10:27

import deshonnati_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deshonnati_app', '0014_auto_20220601_0600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyfeed',
            name='page10',
        ),
        migrations.RemoveField(
            model_name='dailyfeed',
            name='page11',
        ),
        migrations.RemoveField(
            model_name='dailyfeed',
            name='page12',
        ),
        migrations.RemoveField(
            model_name='dailyfeed',
            name='page2',
        ),
        migrations.RemoveField(
            model_name='dailyfeed',
            name='page3',
        ),
        migrations.RemoveField(
            model_name='dailyfeed',
            name='page4',
        ),
        migrations.RemoveField(
            model_name='dailyfeed',
            name='page5',
        ),
        migrations.RemoveField(
            model_name='dailyfeed',
            name='page6',
        ),
        migrations.RemoveField(
            model_name='dailyfeed',
            name='page7',
        ),
        migrations.RemoveField(
            model_name='dailyfeed',
            name='page8',
        ),
        migrations.RemoveField(
            model_name='dailyfeed',
            name='page9',
        ),
        migrations.AlterField(
            model_name='dailyfeed',
            name='page1',
            field=models.FileField(upload_to=deshonnati_app.models.user_directory_path),
        ),
    ]
